name: background_screenshot_app
description: A Flutter desktop app that takes screenshots at regular intervals
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  path_provider: ^2.1.1
  system_tray: ^2.0.3
  window_manager: ^0.3.7
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/app_icon.png
    - assets/app_icon.ico