name: Flutter Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # You can specify a specific Flutter version if needed
          # flutter-version: '3.19.0'
      
      - name: Install dependencies
        run: flutter pub get
        
      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop
        
      - name: Analyze code
        run: flutter analyze
        continue-on-error: true
        
      - name: Run tests
        run: flutter test
        continue-on-error: true
        
      - name: Build Windows app
        run: |
          echo "Building Windows app..."
          flutter build windows --release --verbose
        
      - name: Check build output directory
        run: |
          echo "Checking build output directory..."
          if (Test-Path -Path "build\windows\runner\Release") {
            echo "Build directory exists!"
            Get-ChildItem "build\windows\runner\Release"
          } else {
            echo "Build directory does not exist!"
            echo "Checking alternative paths..."
            if (Test-Path -Path "build\windows") {
              Get-ChildItem "build\windows" -Recurse | Select-Object -First 20
            }
          }
        continue-on-error: true
        
      - name: Package Windows app
        run: |
          echo "Packaging Windows app..."
          if (Test-Path -Path "build\windows\runner\Release") {
            cd build\windows\runner\Release
            7z a -r ..\..\..\..\background_screenshot_app.zip *
            echo "Packaging completed!"
          } elseif (Test-Path -Path "build\windows\x64\runner\Release") {
            cd build\windows\x64\runner\Release
            7z a -r ..\..\..\..\..\background_screenshot_app.zip *
            echo "Packaging completed from x64 path!"
          } else {
            echo "ERROR: Could not find build output directory!"
            exit 1
          }
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: background_screenshot_app.zip
          retention-days: 7